import { useEffect, useState } from 'react'
import { Folder, Eye, Heart, Globe2, HardDrive } from 'lucide-react'
import Avatar, { displayName } from './Avatar.jsx'
import AgentIcon from './AgentIcon.jsx'
import PreviewImage from './PreviewImage.jsx'
import { cn } from '@/lib/utils'
import { LIKED_PROJECTS_KEY, readFavoriteSet, writeFavoriteSet } from '@/lib/favorites'
import { trackEvent } from '@/lib/analytics'
import { useI18n } from '@/i18n.jsx'
import { groupVisibility, isActiveRun } from '@/lib/runVisibility'

const getLikedProjects = () => {
  return readFavoriteSet(LIKED_PROJECTS_KEY)
}

// 项目（case）级点赞，乐观更新 + 服务器广播校准
export function ProjectLikeButton({ project, likes, className }) {
  const { t } = useI18n()
  const [liked, setLiked] = useState(() => getLikedProjects().has(project))
  const [count, setCount] = useState(likes || 0)

  useEffect(() => setCount(likes || 0), [likes])

  const toggle = (e) => {
    e.stopPropagation()
    const next = !liked
    setLiked(next)
    setCount((c) => Math.max(0, c + (next ? 1 : -1)))
    const set = getLikedProjects()
    next ? set.add(project) : set.delete(project)
    writeFavoriteSet(LIKED_PROJECTS_KEY, set)
    fetch(`/api/projects/${encodeURIComponent(project)}/like`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ action: next ? 'like' : 'unlike' }),
    }).catch(() => {})
    trackEvent('project_like', { project, liked: next })
  }

  return (
    <button
      type="button"
      onClick={toggle}
      title={liked ? t('project.unlike') : t('project.like')}
      className={cn(
        'flex cursor-pointer items-center gap-1 font-mono text-[11px] tabular-nums transition-colors',
        liked ? 'text-rose-400' : 'text-white/35 hover:text-rose-300',
        className
      )}
    >
      <Heart className={cn('h-3 w-3', liked && 'fill-rose-400')} />
      {count}
    </button>
  )
}

export function CategoryTag({ category, className }) {
  if (!category) return null
  return (
    <span
      className={cn(
        'rounded border border-white/12 bg-black/50 px-1.5 py-0.5 font-mono text-[9px] tracking-[0.15em] text-white/55 uppercase backdrop-blur',
        className
      )}
    >
      {category}
    </span>
  )
}

export default function ProjectCard({ group: g, views, likes, users, onOpen, onOpenUser }) {
  const { t } = useI18n()
  const running = g.runs.filter(isActiveRun).length
  const done = g.runs.filter((r) => r.status === 'done').length
  const failed = g.runs.length - running - done
  const contributors = [...new Set(g.runs.map((r) => r.user).filter(Boolean))]
  const agents = [...new Map(g.runs.map((r) => [r.agentId, r.color])).entries()]
  // demo 缩略图：优先完成且有截图的 run
  const previewRun = g.runs.find((r) => r.preview && r.status === 'done') || g.runs.find((r) => r.preview)
  const category = g.category || g.runs.find((r) => r.category)?.category
  const visibility = groupVisibility(g)
  const VisibilityIcon = visibility === 'community' ? Globe2 : HardDrive

  return (
    <div
      role="button"
      tabIndex={0}
      onClick={onOpen}
      onKeyDown={(e) => e.key === 'Enter' && onOpen()}
      className={cn(
        'group cursor-pointer overflow-hidden rounded-lg border bg-[#0c0c0f] text-left transition-all hover:-translate-y-0.5',
        running ? 'border-acid/30' : 'border-white/10 hover:border-white/30'
      )}
    >
      {/* demo 效果图 */}
      <div className="relative aspect-[16/10] overflow-hidden border-b border-white/8 bg-black">
        {previewRun ? (
          <PreviewImage
            src={`/api/runs/${previewRun.id}/preview`}
            alt={`${g.project} preview generated by ${previewRun.agentName}`}
          />
        ) : (
          <div className="flex h-full w-full items-center justify-center">
            <Folder className={cn('h-6 w-6', running ? 'text-acid/60' : 'text-white/15')} />
          </div>
        )}
        <CategoryTag category={category} className="absolute top-2 left-2" />
        <div className="absolute top-2 right-2 flex flex-col items-end gap-1.5">
          <span
            className={cn(
              'flex items-center gap-1 rounded border bg-black/70 px-1.5 py-0.5 font-mono text-[8px] tracking-[0.13em] uppercase backdrop-blur',
              visibility === 'community' ? 'border-sky-300/25 text-sky-200' : 'border-amber-300/25 text-amber-200'
            )}
          >
            <VisibilityIcon className="h-2.5 w-2.5" />
            {t(`run.visibility.${visibility}`)}
          </span>
          {running > 0 && (
            <span className="flex items-center gap-1.5 rounded border border-acid/30 bg-black/60 px-1.5 py-0.5 font-mono text-[9px] tracking-[0.15em] text-acid uppercase backdrop-blur">
              <span className="pulse-dot h-1 w-1 rounded-full bg-acid" /> Live
            </span>
          )}
        </div>
      </div>

      <div className="p-4">
        <div className="flex items-center gap-2.5">
          <span className="truncate text-[15px] font-semibold tracking-tight">{g.project}</span>
          <span className="ml-auto flex shrink-0 items-center gap-3">
            <ProjectLikeButton project={g.project} likes={likes} />
            <span className="flex items-center gap-1 font-mono text-[11px] text-white/35 tabular-nums">
              <Eye className="h-3 w-3" />
              {views || 0}
            </span>
          </span>
        </div>

        <div className="mt-3 flex items-center gap-3 font-mono text-[11px] tabular-nums">
          {contributors.length > 0 ? (
            <span
              className="flex min-w-0 items-center gap-1.5"
              title={contributors.join(', ')}
              onClick={(e) => {
                e.stopPropagation()
                onOpenUser?.(contributors[0])
              }}
            >
              <span className="flex shrink-0 -space-x-1.5">
                {contributors.slice(0, 3).map((e) => (
                  <Avatar
                    key={e}
                    email={e}
                    picture={users?.[e]?.picture}
                    className="h-4 w-4 text-[8px] ring-2 ring-[#0c0c0f]"
                  />
                ))}
              </span>
              <span className="truncate text-[10px] text-white/45 transition-colors hover:text-white">
                {displayName(contributors[0], users)}
                {contributors.length > 1 && ` +${contributors.length - 1}`}
              </span>
            </span>
          ) : (
            <span className="flex items-center gap-1.5">
              {agents.map(([agentId, color]) => (
                <AgentIcon key={agentId} agentId={agentId} color={color} className="h-3 w-3" />
              ))}
            </span>
          )}
          <span className="ml-auto flex shrink-0 items-center gap-3">
            <span className="text-[10px] tracking-wider text-white/35 uppercase">{t('project.runsCount', { count: g.runs.length })}</span>
            {running > 0 && (
              <span className="flex items-center gap-1.5 text-acid">
                <span className="pulse-dot h-1.5 w-1.5 rounded-full bg-acid" /> {running}
              </span>
            )}
            {done > 0 && (
              <span className="flex items-center gap-1.5 text-emerald-400">
                <span className="h-1.5 w-1.5 rounded-full bg-emerald-400" /> {done}
              </span>
            )}
            {failed > 0 && (
              <span className="flex items-center gap-1.5 text-red-400/80">
                <span className="h-1.5 w-1.5 rounded-full bg-red-500/80" /> {failed}
              </span>
            )}
          </span>
        </div>
      </div>
    </div>
  )
}
